language: go
go:
- 1.12.x
cache:
  directories:
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod
dist: trusty
script:
- make lint
- make test
- sonar-scanner
after_script:
- make cover
after_success:
- bash <(curl -s https://codecov.io/bash)
addons:
  sonarcloud:
    organization: $ORGANIZATION
    token: $SONAR_TOKEN
env:
  global:
  - GO111MODULE=on
  - secure: F3Z26yo4UezwIJFsS0YWP1byj/mjI9fymfkVGGpIganLD9ozOLU/Ld8icq4ZnXINWcsa7lB+czPYFM0Zpj5uott3VgoXaRcIzLjChx6PTOYUiUwrhCXdI/yGFvQrWs57/0EfUPSYY7XdOtg6YzulB/4/kdzrLEnjbvOUchKf8DlloptKrd9GQuYzcUndedKWzoqxKiJ3BUNrd18MkO4d8nZfw5xc6nxOJZDBhKmnmFX1aMe1kk/gVXvLolfDYVYtllwDDzYLJBVuqTX9db8Utkz3t/OVduFYWaS81pGxp/jVJftqfyknLtCNz62BYJseSOSZen2yKEc+8apsD+Lu4DSqhSUAc90x3jQ25Kg5w5KBaKJls+A6buv2Bdl/zwZu5PgX0bsSOetffZPZbihXnc5U206fnEgaOy5RmYTZlX/21pawZvTUqk3ClaE5DjruePHaLA5/hlgooDx0/uXZtjillgZOE4vIlOm2822Ufi1zEFjLtXAmwWA1TBzmBufYpSIBHFzb4grsZBM+F9EfQ5pAXld4o1cXnHtNXCtvhiQp5gHcHr9fdtq1DyEi2PhhLzVa1TvpFF5gc5n1BYmIfb1ynET4wKd8jcO6tChXqIvqVH9dmbOtAr1LDTt+B3zWuI1tGZ0lKDj0TFUt7EmTuoFHrjw57opnIthlHoRy6bA=
  - secure: du2Vtoc9nqISy6K3fuseqL5PaPd9+JdHnGJwwBSOwznVCLUS8NTBZqe3e8V6RhDeyasrcTNMKtZ0NxfCvV4bt9f0J5Qk3uY57pjXgGr8gswWUYV2X3gJBycOv5WwlxEZKdYMFs6HULKapXeeI4k1WeQA9/vym5jkt7fRWO++y9jEBuzcQ3IsZU64+NDvXLc+Tx/W4osFrJbohqaIN01mCVjxAJs4YI54vzHfCayhAJ7MW60eFlrIjirxLiS5EfMWlbmYG5mfeclGFIljwP7N+x3d4zv3704uBsj1zWDja6PMqVIJEoDWsYQRH4kz0JLpMZJKrCAx/McKmh6VW+nVTkvB5CYBBmKUT5XLqQZ2+LksqETMkKQhUVjlz8ZPWcigoAr+A57hU0FnyxnUU821hLtz2f0MZ85OUvxhYphVokpRD2mxQ3u+YMeOKM++2Dcr/E6FsrzHKhryhxE5b//m9nACVq9QQP+9BEiLtxgvozwT22SWOayfnfjFuZYmxKUjmpFlzWISwCgD1SQ7dpaSaAtmOQQvlP8rUoroIVxaBLalXyoUZH8CaqOc/TjsRQdPejqihPe1CmkCXJExOXKxre0l9xoK0Q/GHIKYsvAWatRk5KkIPWnZRm6Q2sRk8kc0CN/P2jwI+0ouFSNMXikdrmjggMvKBOuy+D0Mn1j5eq0=
  - secure: wCAbyu1RxxFWSKnZ0aQoZe3q8iwB4Jki6Y19Nn4g6YLQrvbbBPfW5hw/J4W8LGryjESGxvS/fPSy44OfPWerRY1RRTUJaRPJDsbH88FiYHV/HWK0ujaFjOS4VwP3CtW+TID6+c9jDW9Zw3eCiRnJ6ltyxWZ37UHY8v+fkfD7vI2wZoIEOjlrsjfJa5lYFDqFXVz5wVxsegunrX6KRMefiAMzS9pZ35JM5rkdOtXXU3+BYgNmM0rjvgNYSvMEHlM+kA+9OoFUg8DRhPa5Joq4d4NTB83yjIsFOQ91B4MvwPRie5oYCnr7IrQVJBCvo4W5d/asJrPkq57c08ovVNkblca/rZ0ndgmCPpbvl4l65W/Y5K97i+TTjUu1BPUW8fBOMh+cS66Duj4y6l/Y3bUOE9VJ1AzYy6k4KBZl9l1pMajO6HzkfdioLs0I2mCj3b699k5blQ2zeidO1S62Otr2VB4BT2xzALTxvC3FTEVL8JNfA/wDRXSFRYGn6tMuInzsiwG8PixfNq6tXjJwqTCaDm7pKZ1cbqMUKwsA4PFb6vpoRJov4kXboZLSgzbyZv3hgZ+MSvLMpcDrVmw99UJ5Qu+oYJ38miCz54JySTzzNPoaFcJM8EnkWIRL59r6CFNuxLdwT4ZpJCYyBcSvWmx5oZwNrwDjx8j2xx5XQFrRtOY=
  - secure: EqFk74WqjWh/oHCE3/2ch27juDxSrNq3MfdNIZtm9wFARn0wR2d25nlgrJZpHkp7QwWGl3wtdP+X+iqJhPOs5NwxIzNEs1X0VTzij3/WpPxAaoQW6uRHXaoqtiZIqnXwJzAIYHPT2oQ5aXAxVmLDD7qIzliOJHwSu0RYLq28daPXFH49NVh2YCYLnvJQ/h5hjsfSAWtqzu688sZMc4EGnL8ZcjFivu9yYZV1tVV8oNnhJlgsKtZ1SEMaso0sAshr5JBJbZne81aBvrAnKaaGg7nh/J7KO9bv70JCVvvcPjNJdmY3gfu1auQTbkcnCS7ZKlreXFOVtVRpQw8fv5+U7QfDC4Ix1mHTxpBu+FVRqooCjPB30WbnIoZ0pyotvURYg7ZV/M15/6Lyaz2iGTivVh2MGRW2E5JN0lvRD4evUX3ODw546n0iKfxfnYyAtaCB1/GNvf+O3MITf6JhASBug/hV+nS7bUVmb6NHjN1+pPEfNMIOPNqpe0AnVHCURV9NDrcJOpZmXGu8YVwmwsG815FCABqkl4ASETbTuF6b8VYGmmpsZ4r6VpsGRLXW6dPGNEZnjzcjLYQFtlMmBOPxhLzvSgds3ieipK4QpEPEYoA3JWZcg3GBzwMaLsUk5OhkVR0KGk/birGXfv9YHUGmBrNFL/4yZnpBgIvhTYYiLjY=
